version: 2.0

jobs:
    build:
        machine: true
        working_directory: ~/pi-image
        steps:
            - checkout
            - run: sudo ./gen-image.sh
            - run: xz -9 pi-image.img
            - store_artifacts:
                path: pi-image.img.xz
                destination: pi-image.img.xz
